const ENV = {
  SUPABASE_URL_CLIENT: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY_CLIENT: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_URL_SERVER: process.env.SUPABASE_URL,
  SUPABASE_ANON_KEY_SERVER: process.env.SUPABASE_ANON_KEY,
};
export default ENV;
