export const QUERY_KEY = {
  USER: "user",
  USER_NICKNAME: "user_nickname",
  MUSICS: "musics",
  POSTS: "posts",
  FOLLOWS: "follows",
  POSTID: "postId",
  EMOTION_PLAYLISTS: "emotionPlaylists",
  SEARCH_USER: "searchUser",
  MY_FRIENDS: "myFriends",
  NICKNAME: "nickname",
  SPOTIFY_ACCESS_TOKEN: "spotifyAccessToken",
  SPOTIFY_PLAYLISTS: "spotifyPlaylists",
  BOOKMARKED_PLAYLISTS: "bookmarkedPlaylists",
};
