import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/RQProviders";
import Header from "./(layout)/header";
import { ToastContainer } from "react-toastify";
import Navigation from "./(layout)/navigation";
import HomeHeader from "./(home)/components/home-header";
import { getUserNickname } from "@/services/home-service";
// import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//닉네임 때문에 RootLayout을 async 함수로 변경
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 닉네임 불러오기
  const nickname: string | undefined = await getUserNickname();
  //닉네임 검사 로직을 여기에 추가했습니다.
  // if (!nickname) {
  //   redirect("/sign-in");
  // }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Navigation />
        <HomeHeader nickname={nickname} />
        <Providers>{children}</Providers>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
