import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/RQProviders";
import Header from "./(layout)/header";
import { ToastContainer } from "react-toastify";
import Navigation from "./(layout)/navigation";
import HomeHeader from "./(home)/components/home-header";
import { getUserId } from "@/services/home-service";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId: string | undefined = await getUserId();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Navigation />

        <Providers>
          <HomeHeader userId={userId} />
          {children}
        </Providers>
        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}
