import Providers from "@/providers/RQProviders";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import HeaderWithZustand from "./(home)/components/home-zustand";
import Navigation from "./(layout)/navigation";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const ownGlyph = localFont({
  src: "./fonts/OwnGlyph.ttf",
  variable: "--font-own-glyph",
  weight: "100",
});

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "400 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${pretendard.variable} ${ownGlyph.variable} antialiased`}>
        <Providers>
          <HeaderWithZustand />
          {children}
        </Providers>
        <ToastContainer position="top-right" autoClose={3000} />
        <Navigation />
      </body>
    </html>
  );
}
