import EMOTION_COOKIE_IMAGE_URL from "@/constants/emotions-url.constant";

const emotions: Record<string, string> = {
  JOY: EMOTION_COOKIE_IMAGE_URL.JOY,
  EXCITED: EMOTION_COOKIE_IMAGE_URL.EXCITED,
  BUTTERFLY: EMOTION_COOKIE_IMAGE_URL.BUTTERFLY,
  GRATEFUL: EMOTION_COOKIE_IMAGE_URL.GRATEFUL,
  CALM: EMOTION_COOKIE_IMAGE_URL.CALM,
  LONELY: EMOTION_COOKIE_IMAGE_URL.LONELY,
  ANXIOUS: EMOTION_COOKIE_IMAGE_URL.ANXIOUS,
  TIRED: EMOTION_COOKIE_IMAGE_URL.TIRED,
  SAD: EMOTION_COOKIE_IMAGE_URL.SAD,
  ANGRY: EMOTION_COOKIE_IMAGE_URL.ANGRY,
};

export const checkEmotion = (emotion: string) => {
  return emotions[emotion] || "존재하지 않는 감정이예요";
};
